#!/usr/bin/env php
<?php
require __DIR__ . '/vendor/autoload.php';


// application.php

require __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Application;

$application = new Application();

$application->add(new \Quiz\Command\RunQuizCommand());
$application->add(new \Quiz\Command\CreateQuizCommand());
$application->run();

// choice of quiz
// quiz
// stats