<?php

namespace App\Representation;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;

final class RenderController extends AbstractController{

    public function render(string $view, array $parameters = [], Response $response = null): Response
    {
        return parent::render($view, $parameters, $response); // TODO: Change the autogenerated stub
    }
}
